apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map-f2ze
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map-f2ze
    app.kubernetes.io/part-of: appstudio
  name: dc-metro-map-f2ze
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: dc-metro-map-f2ze
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: dc-metro-map-f2ze
    spec:
      containers:
      - image: quay.io/qijing/ex-registry-aeow-tenant/appstudio/dc-metro-map-f2ze@sha256:f8968250f50612558ca39fbb5cbba8684cec5ea5158af4382274d23273d80b4a
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
